<?php
 /**
  * Title: Portfolio
  * Slug: constructobuild/portfolio
  * Categories: constructobuild
  */
?>
<!-- wp:group {"metadata":{"name":"Portfolio"},"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","right":"var:preset|spacing|40","bottom":"0","left":"var:preset|spacing|40"},"blockGap":"var:preset|spacing|30"}},"backgroundColor":"background-secondary","className":"constructobuild-section-ff727120-f9f4-11ed-8868-91c866c656bb","layout":{"inherit":true,"type":"constrained"}} -->
<div class="wp-block-group alignfull constructobuild-section-ff727120-f9f4-11ed-8868-91c866c656bb has-background-secondary-background-color has-background" style="padding-top:var(--wp--preset--spacing--50);padding-right:var(--wp--preset--spacing--40);padding-bottom:0;padding-left:var(--wp--preset--spacing--40)"><!-- wp:columns {"verticalAlignment":"center","align":"wide","style":{"spacing":{"blockGap":{"top":"var:preset|spacing|30","left":"var:preset|spacing|30"}}},"className":"constructobuild-section-cf44bf70-dcf9-11ed-b405-5314f98b79fc"} -->
<div class="wp-block-columns alignwide are-vertically-aligned-center constructobuild-section-cf44bf70-dcf9-11ed-b405-5314f98b79fc"><!-- wp:column {"verticalAlignment":"center","className":"constructobuild-section-cf424e70-dcf9-11ed-b405-5314f98b79fc"} -->
<div class="wp-block-column is-vertically-aligned-center constructobuild-section-cf424e70-dcf9-11ed-b405-5314f98b79fc"><!-- wp:group {"style":{"spacing":{"blockGap":"10px"}},"className":"constructobuild-section-cf41b230-dcf9-11ed-b405-5314f98b79fc"} -->
<div class="wp-block-group constructobuild-section-cf41b230-dcf9-11ed-b405-5314f98b79fc"><!-- wp:group {"style":{"spacing":{"blockGap":"10px","margin":{"top":"0","bottom":"0"},"padding":{"bottom":"0"}},"border":{"width":"0px","style":"none"}},"className":"constructobuild-section-9bfa8420-37a2-11ee-b7f8-8f7d8708bd7c","layout":{"type":"flex","flexWrap":"nowrap","orientation":"horizontal"}} -->
<div class="wp-block-group constructobuild-section-9bfa8420-37a2-11ee-b7f8-8f7d8708bd7c" style="border-style:none;border-width:0px;margin-top:0;margin-bottom:0;padding-bottom:0"><!-- wp:separator {"style":{"layout":{"selfStretch":"fixed","flexSize":"30px"}},"backgroundColor":"primary","className":"is-style-default"} -->
<hr class="wp-block-separator has-text-color has-primary-color has-alpha-channel-opacity has-primary-background-color has-background is-style-default"/>
<!-- /wp:separator -->

<!-- wp:group {"style":{"spacing":{"padding":{"top":"0","right":"0","bottom":"0","left":"0"},"blockGap":"var:preset|spacing|30","margin":{"bottom":"0"}},"border":{"radius":"0px","top":{"radius":"75px","width":"0px","style":"none"},"right":{"radius":"75px","width":"0px","style":"none"},"bottom":{"radius":"75px","width":"0px","color":"var:preset|color|foreground","style":"none"},"left":{"radius":"75px","width":"0px","style":"none"}}},"className":"animated animated-fadeInUp constructobuild-section-9bf3f470-37a2-11ee-b7f8-8f7d8708bd7c","layout":{"type":"constrained"}} -->
<div class="wp-block-group animated animated-fadeInUp constructobuild-section-9bf3f470-37a2-11ee-b7f8-8f7d8708bd7c" style="border-radius:0px;border-top-style:none;border-top-width:0px;border-right-style:none;border-right-width:0px;border-bottom-color:var(--wp--preset--color--foreground);border-bottom-style:none;border-bottom-width:0px;border-left-style:none;border-left-width:0px;margin-bottom:0;padding-top:0;padding-right:0;padding-bottom:0;padding-left:0"><!-- wp:paragraph {"align":"left","style":{"typography":{"letterSpacing":"0px","fontSize":"15px"},"spacing":{"margin":{"top":"0","bottom":"0"}}},"textColor":"foreground","className":"animated animated-fadeInUp constructobuild-section-9bf10e40-37a2-11ee-b7f8-8f7d8708bd7c"} -->
<p class="has-text-align-left animated animated-fadeInUp constructobuild-section-9bf10e40-37a2-11ee-b7f8-8f7d8708bd7c has-foreground-color has-text-color" style="margin-top:0;margin-bottom:0;font-size:15px;letter-spacing:0px"><strong> <?php echo esc_html__( 'Selected Projects', 'constructo-build' ); ?></strong></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:heading {"textAlign":"left","style":{"typography":{"textTransform":"capitalize","lineHeight":"1.7"},"spacing":{"margin":{"bottom":"0px"}}},"className":"animated animated-fadeInUp constructobuild-section-cf413d00-dcf9-11ed-b405-5314f98b79fc","fontSize":"slider-title"} -->
<h2 class="wp-block-heading has-text-align-left animated animated-fadeInUp constructobuild-section-cf413d00-dcf9-11ed-b405-5314f98b79fc has-slider-title-font-size" style="margin-bottom:0px;line-height:1.7;text-transform:capitalize"> <?php echo esc_html__( 'Our Showcase', 'constructo-build' ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center","width":"30%","className":"constructobuild-section-cf442330-dcf9-11ed-b405-5314f98b79fc"} -->
<div class="wp-block-column is-vertically-aligned-center constructobuild-section-cf442330-dcf9-11ed-b405-5314f98b79fc" style="flex-basis:30%"><!-- wp:buttons {"className":"animated animated-fadeInUp constructobuild-section-ff552520-f9f4-11ed-8868-91c866c656bb","layout":{"type":"flex","justifyContent":"right"},"style":{"spacing":{"margin":{"top":"0px","bottom":"0px"}}}} -->
<div class="wp-block-buttons animated animated-fadeInUp constructobuild-section-ff552520-f9f4-11ed-8868-91c866c656bb" style="margin-top:0px;margin-bottom:0px"><!-- wp:button {"className":"is-style-outline constructobuild-section-ff5461d0-f9f4-11ed-8868-91c866c656bb"} -->
<div class="wp-block-button is-style-outline constructobuild-section-ff5461d0-f9f4-11ed-8868-91c866c656bb"><a class="wp-block-button__link wp-element-button" href="#"><?php echo esc_html__( 'View More', 'constructo-build' ); ?> </a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:columns {"align":"wide","style":{"spacing":{"blockGap":{"top":"var:preset|spacing|30","left":"var:preset|spacing|30"}}},"className":"constructobuild-section-ff71add0-f9f4-11ed-8868-91c866c656bb"} -->
<div class="wp-block-columns alignwide constructobuild-section-ff71add0-f9f4-11ed-8868-91c866c656bb"><!-- wp:column {"style":{"color":{"background":"#ffb25900"},"spacing":{"padding":{"top":"0","right":"0","bottom":"0","left":"0"}}},"className":"constructobuild-section-ff5b66b0-f9f4-11ed-8868-91c866c656bb"} -->
<div class="wp-block-column constructobuild-section-ff5b66b0-f9f4-11ed-8868-91c866c656bb has-background" style="background-color:#ffb25900;padding-top:0;padding-right:0;padding-bottom:0;padding-left:0"><!-- wp:group {"style":{"spacing":{"padding":{"top":"0","right":"0","bottom":"0","left":"0"}}},"className":"animated animated-fadeInUp constructobuild-section-ff5a7c50-f9f4-11ed-8868-91c866c656bb","layout":{"type":"constrained"}} -->
<div class="wp-block-group animated animated-fadeInUp constructobuild-section-ff5a7c50-f9f4-11ed-8868-91c866c656bb" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0"><!-- wp:cover {"url":"<?php echo esc_url( get_template_directory_uri() );?>/images/portfolio-1.jpg","id":2370,"dimRatio":80,"isUserOverlayColor":true,"minHeight":400,"minHeightUnit":"px","customGradient":"linear-gradient(355deg,rgb(0,0,0) 17%,rgba(0,0,0,0) 100%)","contentPosition":"bottom center","style":{"spacing":{"padding":{"top":"var:preset|spacing|30","right":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"var:preset|spacing|30"}},"border":{"width":"0px","style":"none","radius":"10px"}},"className":"image-zoom-hover constructobuild-section-ff5991f0-f9f4-11ed-8868-91c866c656bb"} -->
<div class="wp-block-cover has-custom-content-position is-position-bottom-center image-zoom-hover constructobuild-section-ff5991f0-f9f4-11ed-8868-91c866c656bb" style="border-style:none;border-width:0px;border-radius:10px;padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--30);min-height:400px"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-80 has-background-dim wp-block-cover__gradient-background has-background-gradient" style="background:linear-gradient(355deg,rgb(0,0,0) 17%,rgba(0,0,0,0) 100%)"></span><img class="wp-block-cover__image-background wp-image-2370" alt="" src="<?php echo esc_url( get_template_directory_uri() );?>/images/portfolio-1.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"style":{"spacing":{"blockGap":"10px"}},"className":"constructobuild-section-ff576f10-f9f4-11ed-8868-91c866c656bb"} -->
<div class="wp-block-group constructobuild-section-ff576f10-f9f4-11ed-8868-91c866c656bb"><!-- wp:paragraph {"style":{"elements":{"link":{"color":{"text":"var:preset|color|primary"}}},"typography":{"fontStyle":"normal","fontWeight":"600"}},"textColor":"primary"} -->
<p class="has-primary-color has-text-color has-link-color" style="font-style:normal;font-weight:600"><em><?php echo esc_html__( 'Finance', 'constructo-build' ); ?> </em></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"textAlign":"left","level":3,"style":{"typography":{"textTransform":"capitalize","fontStyle":"normal","fontWeight":"600","fontSize":"1.5rem"},"elements":{"link":{"color":{"text":"var:preset|color|white"}}}},"textColor":"white","className":"constructobuild-section-ff56abc0-f9f4-11ed-8868-91c866c656bb"} -->
<h3 class="wp-block-heading has-text-align-left constructobuild-section-ff56abc0-f9f4-11ed-8868-91c866c656bb has-white-color has-text-color has-link-color" style="font-size:1.5rem;font-style:normal;font-weight:600;text-transform:capitalize"><a href="#"> <?php echo esc_html__( 'Financial Planning', 'constructo-build' ); ?></a></h3>
<!-- /wp:heading --></div>
<!-- /wp:group --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"style":{"color":{"background":"#ffb25900"},"spacing":{"padding":{"top":"0","right":"0","bottom":"0","left":"0"}}},"className":"constructobuild-section-ff6096d0-f9f4-11ed-8868-91c866c656bb"} -->
<div class="wp-block-column constructobuild-section-ff6096d0-f9f4-11ed-8868-91c866c656bb has-background" style="background-color:#ffb25900;padding-top:0;padding-right:0;padding-bottom:0;padding-left:0"><!-- wp:group {"style":{"spacing":{"padding":{"top":"0","right":"0","bottom":"0","left":"0"}}},"className":"animated animated-fadeInUp constructobuild-section-ff5fd380-f9f4-11ed-8868-91c866c656bb","layout":{"type":"constrained"}} -->
<div class="wp-block-group animated animated-fadeInUp constructobuild-section-ff5fd380-f9f4-11ed-8868-91c866c656bb" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0"><!-- wp:cover {"url":"<?php echo esc_url( get_template_directory_uri() );?>/images/portfolio-2.jpg","id":2357,"dimRatio":80,"isUserOverlayColor":true,"minHeight":400,"minHeightUnit":"px","customGradient":"linear-gradient(0deg,rgb(0,0,0) 18%,rgba(0,0,0,0) 100%)","contentPosition":"bottom center","style":{"spacing":{"padding":{"top":"var:preset|spacing|30","right":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"var:preset|spacing|30"}},"border":{"radius":"10px"}},"className":"image-zoom-hover constructobuild-section-ff5f1030-f9f4-11ed-8868-91c866c656bb"} -->
<div class="wp-block-cover has-custom-content-position is-position-bottom-center image-zoom-hover constructobuild-section-ff5f1030-f9f4-11ed-8868-91c866c656bb" style="border-radius:10px;padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--30);min-height:400px"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-80 has-background-dim wp-block-cover__gradient-background has-background-gradient" style="background:linear-gradient(0deg,rgb(0,0,0) 18%,rgba(0,0,0,0) 100%)"></span><img class="wp-block-cover__image-background wp-image-2357" alt="" src="<?php echo esc_url( get_template_directory_uri() );?>/images/portfolio-2.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"style":{"spacing":{"blockGap":"10px"}},"className":"constructobuild-section-ff5d1460-f9f4-11ed-8868-91c866c656bb"} -->
<div class="wp-block-group constructobuild-section-ff5d1460-f9f4-11ed-8868-91c866c656bb"><!-- wp:paragraph {"style":{"elements":{"link":{"color":{"text":"var:preset|color|primary"}}},"typography":{"fontStyle":"normal","fontWeight":"600"}},"textColor":"primary"} -->
<p class="has-primary-color has-text-color has-link-color" style="font-style:normal;font-weight:600"><em> <?php echo esc_html__( 'Consulting', 'constructo-build' ); ?></em></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"textAlign":"left","level":3,"style":{"typography":{"textTransform":"capitalize","fontStyle":"normal","fontWeight":"600","fontSize":"1.5rem"},"elements":{"link":{"color":{"text":"var:preset|color|white"}}}},"textColor":"white","className":"constructobuild-section-ff5c2a00-f9f4-11ed-8868-91c866c656bb"} -->
<h3 class="wp-block-heading has-text-align-left constructobuild-section-ff5c2a00-f9f4-11ed-8868-91c866c656bb has-white-color has-text-color has-link-color" style="font-size:1.5rem;font-style:normal;font-weight:600;text-transform:capitalize"><a href="#"> <?php echo esc_html__( 'IT Consultations', 'constructo-build' ); ?></a></h3>
<!-- /wp:heading --></div>
<!-- /wp:group --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"style":{"color":{"background":"#ffb25900"},"spacing":{"padding":{"top":"0","right":"0","bottom":"0","left":"0"}}},"className":"constructobuild-section-ff661510-f9f4-11ed-8868-91c866c656bb"} -->
<div class="wp-block-column constructobuild-section-ff661510-f9f4-11ed-8868-91c866c656bb has-background" style="background-color:#ffb25900;padding-top:0;padding-right:0;padding-bottom:0;padding-left:0"><!-- wp:group {"style":{"spacing":{"padding":{"top":"0","right":"0","bottom":"0","left":"0"}}},"className":"animated animated-fadeInUp constructobuild-section-ff6551c0-f9f4-11ed-8868-91c866c656bb","layout":{"type":"constrained"}} -->
<div class="wp-block-group animated animated-fadeInUp constructobuild-section-ff6551c0-f9f4-11ed-8868-91c866c656bb" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0"><!-- wp:cover {"url":"<?php echo esc_url( get_template_directory_uri() );?>/images/portfolio-3.jpg","id":2358,"dimRatio":80,"isUserOverlayColor":true,"minHeight":400,"minHeightUnit":"px","customGradient":"linear-gradient(0deg,rgb(0,0,0) 7%,rgba(0,0,0,0) 100%)","contentPosition":"bottom center","style":{"spacing":{"padding":{"top":"var:preset|spacing|30","right":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"var:preset|spacing|30"}},"border":{"width":"0px","style":"none","radius":"10px"}},"className":"image-zoom-hover constructobuild-section-ff646760-f9f4-11ed-8868-91c866c656bb"} -->
<div class="wp-block-cover has-custom-content-position is-position-bottom-center image-zoom-hover constructobuild-section-ff646760-f9f4-11ed-8868-91c866c656bb" style="border-style:none;border-width:0px;border-radius:10px;padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--30);min-height:400px"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-80 has-background-dim wp-block-cover__gradient-background has-background-gradient" style="background:linear-gradient(0deg,rgb(0,0,0) 7%,rgba(0,0,0,0) 100%)"></span><img class="wp-block-cover__image-background wp-image-2358" alt="" src="<?php echo esc_url( get_template_directory_uri() );?>/images/portfolio-3.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"style":{"spacing":{"blockGap":"10px"}},"className":"constructobuild-section-ff624480-f9f4-11ed-8868-91c866c656bb"} -->
<div class="wp-block-group constructobuild-section-ff624480-f9f4-11ed-8868-91c866c656bb"><!-- wp:paragraph {"style":{"elements":{"link":{"color":{"text":"var:preset|color|primary"}}},"typography":{"fontStyle":"normal","fontWeight":"600"}},"textColor":"primary"} -->
<p class="has-primary-color has-text-color has-link-color" style="font-style:normal;font-weight:600"><em><?php echo esc_html__( 'Business', 'constructo-build' ); ?> </em></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"textAlign":"left","level":3,"style":{"typography":{"textTransform":"capitalize","fontStyle":"normal","fontWeight":"600","fontSize":"1.5rem"},"elements":{"link":{"color":{"text":"var:preset|color|white"}}}},"textColor":"white","className":"constructobuild-section-ff618130-f9f4-11ed-8868-91c866c656bb"} -->
<h3 class="wp-block-heading has-text-align-left constructobuild-section-ff618130-f9f4-11ed-8868-91c866c656bb has-white-color has-text-color has-link-color" style="font-size:1.5rem;font-style:normal;font-weight:600;text-transform:capitalize"><a href="#"> <?php echo esc_html__( 'Business Monitor', 'constructo-build' ); ?></a></h3>
<!-- /wp:heading --></div>
<!-- /wp:group --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:columns {"align":"wide","style":{"spacing":{"blockGap":{"top":"var:preset|spacing|30","left":"var:preset|spacing|30"}}},"className":"constructobuild-section-ff71add0-f9f4-11ed-8868-91c866c656bb"} -->
<div class="wp-block-columns alignwide constructobuild-section-ff71add0-f9f4-11ed-8868-91c866c656bb"><!-- wp:column {"style":{"color":{"background":"#ffb25900"},"spacing":{"padding":{"top":"0","right":"0","bottom":"0","left":"0"}}},"className":"constructobuild-section-ff6096d0-f9f4-11ed-8868-91c866c656bb"} -->
<div class="wp-block-column constructobuild-section-ff6096d0-f9f4-11ed-8868-91c866c656bb has-background" style="background-color:#ffb25900;padding-top:0;padding-right:0;padding-bottom:0;padding-left:0"><!-- wp:group {"style":{"spacing":{"padding":{"top":"0","right":"0","bottom":"0","left":"0"}}},"className":"animated animated-fadeInUp constructobuild-section-ff5fd380-f9f4-11ed-8868-91c866c656bb","layout":{"type":"constrained"}} -->
<div class="wp-block-group animated animated-fadeInUp constructobuild-section-ff5fd380-f9f4-11ed-8868-91c866c656bb" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0"><!-- wp:cover {"url":"<?php echo esc_url( get_template_directory_uri() );?>/images/portfolio-2.jpg","id":2357,"dimRatio":80,"isUserOverlayColor":true,"minHeight":400,"minHeightUnit":"px","customGradient":"linear-gradient(0deg,rgb(5,5,5) 0%,rgba(10,10,10,0.01) 100%)","contentPosition":"bottom center","style":{"spacing":{"padding":{"top":"var:preset|spacing|30","right":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"var:preset|spacing|30"}},"border":{"radius":"10px"}},"className":"image-zoom-hover constructobuild-section-ff5f1030-f9f4-11ed-8868-91c866c656bb"} -->
<div class="wp-block-cover has-custom-content-position is-position-bottom-center image-zoom-hover constructobuild-section-ff5f1030-f9f4-11ed-8868-91c866c656bb" style="border-radius:10px;padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--30);min-height:400px"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-80 has-background-dim wp-block-cover__gradient-background has-background-gradient" style="background:linear-gradient(0deg,rgb(5,5,5) 0%,rgba(10,10,10,0.01) 100%)"></span><img class="wp-block-cover__image-background wp-image-2357" alt="" src="<?php echo esc_url( get_template_directory_uri() );?>/images/portfolio-2.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"style":{"spacing":{"blockGap":"10px"}},"className":"constructobuild-section-ff5d1460-f9f4-11ed-8868-91c866c656bb"} -->
<div class="wp-block-group constructobuild-section-ff5d1460-f9f4-11ed-8868-91c866c656bb"><!-- wp:paragraph {"style":{"elements":{"link":{"color":{"text":"var:preset|color|primary"}}},"typography":{"fontStyle":"normal","fontWeight":"600"}},"textColor":"primary"} -->
<p class="has-primary-color has-text-color has-link-color" style="font-style:normal;font-weight:600"><em> <?php echo esc_html__( 'Finance', 'constructo-build' ); ?></em></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"textAlign":"left","level":3,"style":{"typography":{"textTransform":"capitalize","fontStyle":"normal","fontWeight":"600","fontSize":"1.5rem"},"elements":{"link":{"color":{"text":"var:preset|color|white"}}}},"textColor":"white","className":"constructobuild-section-ff5c2a00-f9f4-11ed-8868-91c866c656bb"} -->
<h3 class="wp-block-heading has-text-align-left constructobuild-section-ff5c2a00-f9f4-11ed-8868-91c866c656bb has-white-color has-text-color has-link-color" style="font-size:1.5rem;font-style:normal;font-weight:600;text-transform:capitalize"><a href="#"> <?php echo esc_html__( 'IT Consultations', 'constructo-build' ); ?></a></h3>
<!-- /wp:heading --></div>
<!-- /wp:group --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"style":{"color":{"background":"#ffb25900"},"spacing":{"padding":{"top":"0","right":"0","bottom":"0","left":"0"}}},"className":"constructobuild-section-ff6b4530-f9f4-11ed-8868-91c866c656bb"} -->
<div class="wp-block-column constructobuild-section-ff6b4530-f9f4-11ed-8868-91c866c656bb has-background" style="background-color:#ffb25900;padding-top:0;padding-right:0;padding-bottom:0;padding-left:0"><!-- wp:group {"style":{"spacing":{"padding":{"top":"0","right":"0","bottom":"0","left":"0"}}},"className":"animated animated-fadeInUp constructobuild-section-ff6a81e0-f9f4-11ed-8868-91c866c656bb","layout":{"type":"constrained"}} -->
<div class="wp-block-group animated animated-fadeInUp constructobuild-section-ff6a81e0-f9f4-11ed-8868-91c866c656bb" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0"><!-- wp:cover {"url":"<?php echo esc_url( get_template_directory_uri() );?>/images/portfolio-4.jpg","id":2359,"dimRatio":80,"isUserOverlayColor":true,"minHeight":400,"minHeightUnit":"px","customGradient":"linear-gradient(0deg,rgb(2,2,2) 0%,rgba(2,2,2,0.03) 100%)","contentPosition":"bottom center","style":{"spacing":{"padding":{"top":"var:preset|spacing|30","right":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"var:preset|spacing|30"}},"border":{"radius":"10px"}},"className":"image-zoom-hover constructobuild-section-ff69be90-f9f4-11ed-8868-91c866c656bb"} -->
<div class="wp-block-cover has-custom-content-position is-position-bottom-center image-zoom-hover constructobuild-section-ff69be90-f9f4-11ed-8868-91c866c656bb" style="border-radius:10px;padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--30);min-height:400px"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-80 has-background-dim wp-block-cover__gradient-background has-background-gradient" style="background:linear-gradient(0deg,rgb(2,2,2) 0%,rgba(2,2,2,0.03) 100%)"></span><img class="wp-block-cover__image-background wp-image-2359" alt="" src="<?php echo esc_url( get_template_directory_uri() );?>/images/portfolio-4.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"style":{"spacing":{"blockGap":"10px"}},"className":"constructobuild-section-ff67c2c0-f9f4-11ed-8868-91c866c656bb"} -->
<div class="wp-block-group constructobuild-section-ff67c2c0-f9f4-11ed-8868-91c866c656bb"><!-- wp:paragraph {"style":{"elements":{"link":{"color":{"text":"var:preset|color|primary"}}},"typography":{"fontStyle":"normal","fontWeight":"600"}},"textColor":"primary"} -->
<p class="has-primary-color has-text-color has-link-color" style="font-style:normal;font-weight:600"><em> <?php echo esc_html__( 'Finance', 'constructo-build' ); ?></em></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"textAlign":"left","level":3,"style":{"typography":{"textTransform":"capitalize","fontStyle":"normal","fontWeight":"600","fontSize":"1.5rem"},"elements":{"link":{"color":{"text":"var:preset|color|white"}}}},"textColor":"white","className":"constructobuild-section-ff66d860-f9f4-11ed-8868-91c866c656bb"} -->
<h3 class="wp-block-heading has-text-align-left constructobuild-section-ff66d860-f9f4-11ed-8868-91c866c656bb has-white-color has-text-color has-link-color" style="font-size:1.5rem;font-style:normal;font-weight:600;text-transform:capitalize"><a href="#"> <?php echo esc_html__( 'Digital Strategy', 'constructo-build' ); ?></a></h3>
<!-- /wp:heading --></div>
<!-- /wp:group --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"style":{"color":{"background":"#ffb25900"},"spacing":{"padding":{"top":"0","right":"0","bottom":"0","left":"0"}}},"className":"constructobuild-section-ff70ea80-f9f4-11ed-8868-91c866c656bb"} -->
<div class="wp-block-column constructobuild-section-ff70ea80-f9f4-11ed-8868-91c866c656bb has-background" style="background-color:#ffb25900;padding-top:0;padding-right:0;padding-bottom:0;padding-left:0"><!-- wp:group {"style":{"spacing":{"padding":{"top":"0","right":"0","bottom":"0","left":"0"}}},"className":"animated animated-fadeInUp constructobuild-section-ff700020-f9f4-11ed-8868-91c866c656bb","layout":{"type":"constrained"}} -->
<div class="wp-block-group animated animated-fadeInUp constructobuild-section-ff700020-f9f4-11ed-8868-91c866c656bb" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0"><!-- wp:cover {"url":"<?php echo esc_url( get_template_directory_uri() );?>/images/portfolio-5.jpg","id":2361,"dimRatio":90,"isUserOverlayColor":true,"minHeight":400,"minHeightUnit":"px","customGradient":"linear-gradient(0deg,rgba(0,0,0,0.99) 0%,rgba(5,5,5,0.01) 100%)","contentPosition":"bottom center","style":{"spacing":{"padding":{"top":"var:preset|spacing|30","right":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"var:preset|spacing|30"}},"border":{"radius":"10px"}},"className":"image-zoom-hover constructobuild-section-ff6f15c0-f9f4-11ed-8868-91c866c656bb"} -->
<div class="wp-block-cover has-custom-content-position is-position-bottom-center image-zoom-hover constructobuild-section-ff6f15c0-f9f4-11ed-8868-91c866c656bb" style="border-radius:10px;padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--30);min-height:400px"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-90 has-background-dim wp-block-cover__gradient-background has-background-gradient" style="background:linear-gradient(0deg,rgba(0,0,0,0.99) 0%,rgba(5,5,5,0.01) 100%)"></span><img class="wp-block-cover__image-background wp-image-2361" alt="" src="<?php echo esc_url( get_template_directory_uri() );?>/images/portfolio-5.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"style":{"spacing":{"blockGap":"10px"}},"className":"constructobuild-section-ff6cf2e0-f9f4-11ed-8868-91c866c656bb"} -->
<div class="wp-block-group constructobuild-section-ff6cf2e0-f9f4-11ed-8868-91c866c656bb"><!-- wp:paragraph {"style":{"elements":{"link":{"color":{"text":"var:preset|color|primary"}}},"typography":{"fontStyle":"normal","fontWeight":"600"}},"textColor":"primary"} -->
<p class="has-primary-color has-text-color has-link-color" style="font-style:normal;font-weight:600"><em> <?php echo esc_html__( 'Finance', 'constructo-build' ); ?></em></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"textAlign":"left","level":3,"style":{"typography":{"textTransform":"capitalize","fontStyle":"normal","fontWeight":"600","fontSize":"1.5rem"},"elements":{"link":{"color":{"text":"var:preset|color|white"}}}},"textColor":"white","className":"constructobuild-section-ff6c2f90-f9f4-11ed-8868-91c866c656bb"} -->
<h3 class="wp-block-heading has-text-align-left constructobuild-section-ff6c2f90-f9f4-11ed-8868-91c866c656bb has-white-color has-text-color has-link-color" style="font-size:1.5rem;font-style:normal;font-weight:600;text-transform:capitalize"><a href="#"> <?php echo esc_html__( 'Free Consulting', 'constructo-build' ); ?></a></h3>
<!-- /wp:heading --></div>
<!-- /wp:group --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->